/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/linker/ng_module_factory';
import * as import1 from './sub.module';
import * as import2 from '@angular/router/src/router_module';
import * as import3 from '@angular/core/src/di/injector';
import * as import4 from './sub-home.component.ngfactory';
import * as import5 from './summary.component.ngfactory';
import * as import6 from './detail.component.ngfactory';
import * as import7 from './sub-home.component';
import * as import8 from './summary.component';
import * as import9 from './detail.component';
import * as import10 from '@angular/router/src/router_config_loader';
import * as import11 from '@angular/core/src/i18n/tokens';
class SubModuleInjector extends import0.NgModuleInjector<import1.SubModule> {
  _RouterModule_0:import2.RouterModule;
  _SubModule_1:import1.SubModule;
  __ROUTES_2:any[];
  __LOCALE_ID_3:any;
  __TRANSLATIONS_FORMAT_4:any;
  constructor(parent:import3.Injector) {
    super(parent,[
      import4.SubHomeComponentNgFactory,
      import5.SummaryComponentNgFactory,
      import6.DetailComponentNgFactory
    ]
    ,[]);
  }
  get _ROUTES_2():any[] {
        if ((this.__ROUTES_2 == (null as any))) { (this.__ROUTES_2 = [[{
          path: '',
          component: import7.SubHomeComponent,
          children: [
            {
              path: '',
              component: import8.SummaryComponent
            }
            ,
            {
              path: 'detail',
              component: import9.DetailComponent
            }

          ]

        }
    ]]); }
    return this.__ROUTES_2;
  }
  get _LOCALE_ID_3():any {
    if ((this.__LOCALE_ID_3 == (null as any))) { (this.__LOCALE_ID_3 = (null as any)); }
    return this.__LOCALE_ID_3;
  }
  get _TRANSLATIONS_FORMAT_4():any {
    if ((this.__TRANSLATIONS_FORMAT_4 == (null as any))) { (this.__TRANSLATIONS_FORMAT_4 = (null as any)); }
    return this.__TRANSLATIONS_FORMAT_4;
  }
  createInternal():import1.SubModule {
    this._RouterModule_0 = new import2.RouterModule(this.parent.get(import2.ROUTER_FORROOT_GUARD,(null as any)));
    this._SubModule_1 = new import1.SubModule();
    return this._SubModule_1;
  }
  getInternal(token:any,notFoundResult:any):any {
    if ((token === import2.RouterModule)) { return this._RouterModule_0; }
    if ((token === import1.SubModule)) { return this._SubModule_1; }
    if ((token === import10.ROUTES)) { return this._ROUTES_2; }
    if ((token === import11.LOCALE_ID)) { return this._LOCALE_ID_3; }
    if ((token === import11.TRANSLATIONS_FORMAT)) { return this._TRANSLATIONS_FORMAT_4; }
    return notFoundResult;
  }
  destroyInternal():void {
  }
}
export const SubModuleNgFactory:import0.NgModuleFactory<import1.SubModule> = new import0.NgModuleFactory(SubModuleInjector,import1.SubModule);